# Generated by Django 4.0.3 on 2022-03-27 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_copa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeonato',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
